spring.application.name=claimsystem

# Database Configuration (Uses Railway variables online, defaults to your local DB if they aren't found)
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:claimsystem}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:Vinothan1510%}

# Hibernate / JPA Settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.com.vinothan.claimsystem=DEBUG

# JWT Configurations
jwt.secret=${JWT_SECRET:vinothan-secret-key-1234567890-ThisIsForMyPrivateProject}
jwt.expiration=3600000

# Server Port (Railway injects the ${PORT} variable automatically. Defaults to 8080 locally)
server.port=${PORT:8080}